import { ShoppingItem } from "../../types/shopping";

function formatQuantity(
  item: ShoppingItem
) {
  return item.quantity?.trim() ?? "";
}

export function buildGroceryShareText(
  items: ShoppingItem[]
) {
  const remainingItems =
    items.filter(
      (item) => !item.purchased
    );

  if (
    remainingItems.length === 0
  ) {
    return "";
  }

  const groupedItems =
    remainingItems.reduce<
      Record<
        string,
        ShoppingItem[]
      >
    >((groups, item) => {
      const category =
        item.category?.trim() ||
        "Other";

      if (!groups[category]) {
        groups[category] = [];
      }

      groups[category].push(
        item
      );

      return groups;
    }, {});

  const lines: string[] = [
    "🛒 Kitchen Brain — Grocery List",
    "",
  ];

  Object.entries(
    groupedItems
  ).forEach(
    ([
      category,
      categoryItems,
    ]) => {
      lines.push(
        `📌 ${category}`
      );

      categoryItems.forEach(
        (item) => {
          const quantity =
            formatQuantity(
              item
            );

          lines.push(
            quantity
              ? `☐ ${item.name} — ${quantity}`
              : `☐ ${item.name}`
          );
        }
      );

      lines.push("");
    }
  );

  lines.push(
    `Total: ${remainingItems.length} ${
      remainingItems.length === 1
        ? "item"
        : "items"
    }`
  );

  lines.push("");
  lines.push(
    "Generated by Kitchen Brain"
  );

  return lines.join("\n");
}

export async function shareGroceryList(
  items: ShoppingItem[]
) {
  const text =
    buildGroceryShareText(
      items
    );

  if (!text) {
    return {
      success: false,
      method:
        "empty" as const,
    };
  }

  if (
    typeof navigator !==
      "undefined" &&
    typeof navigator.share ===
      "function"
  ) {
    try {
      await navigator.share({
        title:
          "Kitchen Brain Grocery List",
        text,
      });

      return {
        success: true,
        method:
          "share" as const,
      };
    } catch (error) {
      if (
        error instanceof
          DOMException &&
        error.name ===
          "AbortError"
      ) {
        return {
          success: false,
          method:
            "cancelled" as const,
        };
      }
    }
  }

  if (
    typeof navigator !==
      "undefined" &&
    navigator.clipboard
  ) {
    await navigator.clipboard.writeText(
      text
    );

    return {
      success: true,
      method:
        "clipboard" as const,
    };
  }

  return {
    success: false,
    method:
      "unsupported" as const,
  };
}